### ISSUE TITLE
Gnome Shell crashes when dragging window to other screen

### ISSUE THREAD

**Issue by 2i** [itprojects/place.windows.in.center#3]
- OS: Fedora 21; Gnome Shell 3.14.4; 
- second screen connected
- dragging Firefox window from primary screen to secondary → Gnome Shell crashes

**Comment by itprojects** [comment]
This may be due to gnome-shell 3.14.4. In any case this extension was made for 3.12. Please consider the following:

You can center windows without an extension by ticking in dconf editor:

org.gnome.mutter.center-new-windows
